### ISSUE TITLE
Analyze and summarize characteristics of existing services

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-voting#14]
- Tried out and learn how existing voting applications work:
- An example of a digital web ballot created by Stanford for PB in Vallejo: https://pbstanford.org/vallejo/ 
- Another system (which you can try but seems not to be working): https://vota1.agoravoting.com/#/admin/login
- Helios voting: https://vote.heliosvoting.org/
- Summarize your learnings about how these systems work and what can we learn from them

**Comment by ryanchurch6** [comment]
https://docs.google.com/a/berkeley.edu/document/d/1y157sGpmmjWcLMKgGaauW4DzUmLGwsM1CX50I-0urSk/edit?usp=sharing

**Comment by cdparra** [comment]
Great! Now based on examples from this document, let's create our first version of our Data Model
