### ISSUE TITLE
Investigate UI components for voting

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-voting#5]
- How to represent voting options (icons? words? buttons?)
- How to represent proposals in which the user has already voted
- Are there tabs? Categories? (e.g., Archived?)
- Design a UI for delegation, using Mitar's Peer-to-peer voting scheme

**Comment by jennyfromtheweb** [comment]
Main focus: range voting
[Link to Google doc with details on UI ideas/development](https://docs.google.com/a/berkeley.edu/document/d/1-xXRhZ0c34AXD_k_2yvDJ2FGnNQA40IRSUSBdUBEncs/edit)
