### ISSUE TITLE
Make pro/con list of types of voting

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-voting#6]
_From @subjective on March 16, 2015 23:22_
- Arguments for and against each type of voting
- Which is more fair?
- Hypothetical situations, e.g., few people? More than 1000 people?
- Research analyses of the use of different voting systems in social movements and organizations

_Copied from original issue: democracy/voting#3_

**Comment by cdparra** [comment]
_From @maxgrunberg on March 30, 2015 23:15_

Unranked 
-   Pros
  o   one person, one vote (simple)
  o   Moderation (no extremist positions)
-   Cons

o   Tactical voting → compromising: "All votes for anyone other than the second place are votes for the winner"
o   A lot of power is given to the media
o   The system may promote votes against more so than votes for and will probably result in a two proposal system
o   Wasted votes
o   Spoiler effect (split of votes between two similiar proposals)
o   Risk of the focus on a certain proposal, not much need to read the other proposals, if you have a favorite proposal from the beginning

Ranked/distribution
-   Pros
  o   Consensual, more democratic?
  o   closer analysis of the different options
  o   Resistance to tactical voting
  o   Uniqueness of votes
-   Cons
  o    spoiler effect, even stronger than in the unranked

**Comment by ghost** [comment]
Related: http://plato.stanford.edu/entries/voting-methods/

**Comment by ghost** [comment]
Related: http://www.electology.org/#!approval-voting-versus-irv/c1mmu

**Comment by cdparra** [comment]
Regarding existing system, below are three opensource projects oriented to the support of **elections**. They might have ranked/unranked voting algorithm in their code already implemented (although, embedded in their own web apps, not sure if available through APIs. 
- [Agora Voting](https://agoravoting.com/) => [Source Code](https://github.com/agoravoting/agora-ciudadana) | [API](https://agora-ciudadana.readthedocs.org/en/latest/)
- [Helios Voting](https://vote.heliosvoting.org/): [Source Code](https://github.com/benadida/helios-server)
- [Textizen](https://www.textizen.com) (let's likely, but might worth the time looking): [source code](https://github.com/codeforamerica/textizen) | [API](https://textizen.com/api/)

**Comment by ghost** [comment]
Example of tactical voting in UK elections: http://voteswap.org/
