### ISSUE TITLE
Start voting library

### ISSUE THREAD

**Issue by ghost** [socialappslab/appcivist-voting#8]
- List of operations
- Data model

**Comment by cdparra** [comment]
Maybe include binomial proportion confidence interval if the versioning team will use it

**Comment by cdparra** [comment]
Priorities:
- Range
- Unranked

**Comment by maxgrunberg** [comment]
https://docs.google.com/document/d/1-BJqXQ7YJ-AK45xGmnF2SNLRMs7sbM-_uhGNuR69iPk/edit
