### ISSUE TITLE
Voting report

### ISSUE THREAD

**Issue by ghost** [socialappslab/appcivist-voting#9]
- Case studies
- Comparison of voting systems
- Critique beyond national electoral concerns and purely mathematical/formalistic issues
#6

**Comment by gbede9516** [comment]
I was researching existing software doing online democracy and a really popular one is Liquid Democracy which uses the Schulze voting method, and also proxy voting. Maybe these are things we could discuss to see how we can compare/compete with other existing platforms.

**Comment by cdparra** [comment]
Met with @ayeshao 
Her focus of these two weeks will only be meet once with @maxgrunberg and see how she can contribute to the final report

**Comment by cdparra** [comment]
The last known version of the report is [here](https://docs.google.com/document/d/1-BJqXQ7YJ-AK45xGmnF2SNLRMs7sbM-_uhGNuR69iPk/edit?pli=1)

**Comment by cdparra** [comment]
[Final report](https://docs.google.com/document/d/1BWKPuS-fkdOb211fJf2S2ksKiFUItx_4Y8aGt1TbymU/edit?usp=sharing)
